name: build
#
on:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      shell: bash
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"Triggered Build"* ]]; then
            echo "Skipping operation due to 'Bot Triggered Build' message."
            exit 0
        fi
        
        curl https://jenkins.runnable.run/job/xminder/buildWithParameters \
        --user asher:${{ secrets.JENKINS_TOKEN }} \
        --data id=123 --data verbosity=high
      id: vars